apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - core-app
  - copy-engine
  - broker-adapters
  - mt5-bridge-gateway
  - gateway
  - admin-portal
  - async
