package com.nectrix.coreapp.crypto;

import com.nectrix.coreapp.crypto.api.EncryptedField;
import com.nectrix.coreapp.crypto.api.EnvelopeEncryptionService;
import com.nectrix.coreapp.crypto.kms.EnvelopeKmsClient;
import com.nectrix.coreapp.crypto.registry.KeyVersionRepository;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.security.SecureRandom;
import java.util.Arrays;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import org.springframework.stereotype.Service;

/**
 * Real KMS-backed envelope encryption (docs/17-security-architecture.md §17.2,
 * docs/07-auth-onboarding-broker-linking.md §7.8): a fresh per-record AES-256 Data Encryption Key
 * (DEK) is generated by KMS for every {@link #encryptField} call — never reused across records —
 * the plaintext is encrypted locally with it (AES-GCM, fast, no KMS round trip per byte), and the
 * plaintext DEK is zeroed immediately after use, kept only in its KMS-wrapped form alongside the
 * field ciphertext. Decrypting requires asking KMS to unwrap that specific DEK — the KEK itself
 * never leaves KMS.
 */
@Service
public class EnvelopeEncryptionServiceImpl implements EnvelopeEncryptionService {

  private static final String ALGORITHM = "AES/GCM/NoPadding";
  private static final int GCM_TAG_LENGTH_BITS = 128;
  private static final int NONCE_LENGTH_BYTES = 12;

  private final EnvelopeKmsClient kmsClient;
  private final KeyVersionRepository keyVersionRepository;
  private final SecureRandom random = new SecureRandom();

  public EnvelopeEncryptionServiceImpl(
      EnvelopeKmsClient kmsClient, KeyVersionRepository keyVersionRepository) {
    this.kmsClient = kmsClient;
    this.keyVersionRepository = keyVersionRepository;
  }

  @Override
  public EncryptedField encryptField(String plaintext) {
    KeyVersionRepository.CurrentKey current = keyVersionRepository.current();
    EnvelopeKmsClient.DataKey dataKey = kmsClient.generateDataKey(current.kmsKeyId());
    try {
      byte[] nonce = new byte[NONCE_LENGTH_BYTES];
      random.nextBytes(nonce);
      Cipher cipher = Cipher.getInstance(ALGORITHM);
      cipher.init(
          Cipher.ENCRYPT_MODE,
          new SecretKeySpec(dataKey.plaintextKey(), "AES"),
          new GCMParameterSpec(GCM_TAG_LENGTH_BITS, nonce));
      byte[] fieldCiphertext = cipher.doFinal(plaintext.getBytes(StandardCharsets.UTF_8));
      String packed = pack(nonce, dataKey.encryptedKey(), fieldCiphertext);
      return new EncryptedField(packed, current.version());
    } catch (GeneralSecurityException e) {
      throw new IllegalStateException("Failed to encrypt field", e);
    } finally {
      Arrays.fill(dataKey.plaintextKey(), (byte) 0);
    }
  }

  @Override
  public String decryptField(String ciphertext, short keyVersion) {
    String kmsKeyId = keyVersionRepository.kmsKeyIdForVersion(keyVersion);
    Unpacked unpacked = unpack(ciphertext);
    byte[] dek = kmsClient.decryptDataKey(kmsKeyId, unpacked.encryptedDek());
    try {
      Cipher cipher = Cipher.getInstance(ALGORITHM);
      cipher.init(
          Cipher.DECRYPT_MODE,
          new SecretKeySpec(dek, "AES"),
          new GCMParameterSpec(GCM_TAG_LENGTH_BITS, unpacked.nonce()));
      byte[] plaintext = cipher.doFinal(unpacked.fieldCiphertext());
      return new String(plaintext, StandardCharsets.UTF_8);
    } catch (GeneralSecurityException e) {
      throw new IllegalStateException("Failed to decrypt field", e);
    } finally {
      Arrays.fill(dek, (byte) 0);
    }
  }

  // Wire format: [4-byte encryptedDek length][encryptedDek][12-byte nonce][fieldCiphertext+tag],
  // base64-encoded as a single opaque string for the "ciphertext" column.
  private static String pack(byte[] nonce, byte[] encryptedDek, byte[] fieldCiphertext) {
    ByteBuffer buf =
        ByteBuffer.allocate(4 + encryptedDek.length + nonce.length + fieldCiphertext.length);
    buf.putInt(encryptedDek.length);
    buf.put(encryptedDek);
    buf.put(nonce);
    buf.put(fieldCiphertext);
    return Base64.getEncoder().encodeToString(buf.array());
  }

  private record Unpacked(byte[] encryptedDek, byte[] nonce, byte[] fieldCiphertext) {}

  private static Unpacked unpack(String packed) {
    ByteBuffer buf = ByteBuffer.wrap(Base64.getDecoder().decode(packed));
    int dekLength = buf.getInt();
    byte[] encryptedDek = new byte[dekLength];
    buf.get(encryptedDek);
    byte[] nonce = new byte[NONCE_LENGTH_BYTES];
    buf.get(nonce);
    byte[] fieldCiphertext = new byte[buf.remaining()];
    buf.get(fieldCiphertext);
    return new Unpacked(encryptedDek, nonce, fieldCiphertext);
  }
}
