import Link from "next/link";
import { ApiError, beginTwoFactorEnrollment } from "@nectrix/api-client";
import { coreAppBaseUrl } from "@/lib/core-app";
import { requireSession } from "@/lib/auth";
import { DisableTwoFactorForm } from "./DisableTwoFactorForm";
import { TwoFactorVerifyForm } from "./TwoFactorVerifyForm";

// Sample codes only — TwoFactorService has no real backup-code generation yet, matching
// TwoFactorController's original scope (docs/14-api-specification.md §14.2 lists only /2fa/enable
// and /2fa/verify). "Disable two-factor authentication" (DisableTwoFactorForm) IS real, wired to a
// real /2fa/disable endpoint added as a TICKET-117 bugfix — it used to ship as a permanently inert
// button before that endpoint existed.
const SAMPLE_BACKUP_CODES = ["7K2M-9QLX", "4RT8-2FCN", "L9X1-6VBQ", "P3W7-0ZDK"];

function BackToProfile() {
  return (
    <Link
      href="/profile"
      className="mb-4.5 inline-flex items-center gap-1.5 rounded-[9px] border border-[var(--border)] px-3 py-1.5 text-[13px] font-medium text-[var(--text-2)] transition-colors hover:bg-[var(--surface-2)]"
    >
      <svg viewBox="0 0 24 24" width={14} height={14} fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
        <path d="M19 12H5M12 19l-7-7 7-7" />
      </svg>
      Back to profile
    </Link>
  );
}

function EnabledView() {
  return (
    <div className="mx-auto max-w-[600px]">
      <BackToProfile />
      <div className="mb-5.5">
        <h1 className="text-[23px] font-semibold tracking-tight text-[var(--text)]">
          Two-factor authentication
        </h1>
        <p className="mt-1.5 text-[14px] text-[var(--text-2)]">
          Secures your Nectrix sign-in with a one-time code, in addition to your password.
        </p>
      </div>

      <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6">
        <div className="mb-4.5 flex items-center gap-3">
          <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[var(--pos)]/13 text-[var(--pos)]">
            <svg viewBox="0 0 24 24" width={22} height={22} fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
              <path d="M20 6L9 17l-5-5" />
            </svg>
          </div>
          <div>
            <div className="text-[15px] font-semibold text-[var(--text)]">2FA is enabled</div>
            <div className="mt-0.5 text-[12.5px] text-[var(--text-3)]">
              Codes are generated by your authenticator app
            </div>
          </div>
        </div>
        <div className="border-t border-[var(--border)] pt-4">
          <div className="mb-2.5 text-[12px] font-semibold uppercase tracking-[.04em] text-[var(--text-3)]">
            Backup codes
          </div>
          <div className="mb-4.5 grid grid-cols-2 gap-2 font-mono text-[13px] text-[var(--text-2)]">
            {SAMPLE_BACKUP_CODES.map((code) => (
              <div key={code} className="rounded-[8px] bg-[var(--surface-2)] px-2.5 py-2">
                {code}
              </div>
            ))}
          </div>
          <DisableTwoFactorForm />
        </div>
      </div>
    </div>
  );
}

/**
 * Mirrors Nectrix.dc.html's `SHARED · 2FA ENROLLMENT` (`vTwoFA`) — the enrollment flow itself
 * (`beginTwoFactorEnrollment`/`verifyTwoFactor`, TICKET-005) is real and unchanged; this rebuilds
 * the page around the mock's actual layout (numbered steps, "Not enabled" badge, enabled-state card
 * with backup codes + disable button) instead of the plain unstyled version this page shipped as.
 *
 * `session.twoFactorEnabled` is a JWT snapshot as of token-issue time (see lib/session.ts) — it can
 * lag a few minutes behind reality (e.g. right after enrolling, before the next login/refresh). If
 * it's stale-false, calling `beginTwoFactorEnrollment` on an already-enabled account used to
 * silently reset it back to disabled (TwoFactorService.beginEnrollment unconditionally overwrote
 * the confirmed secret) — now guarded server-side (TwoFactorAlreadyEnabledException, 409), caught
 * here to fall back to the enabled view instead of erroring or re-disabling anything.
 */
export default async function TwoFactorSettingsPage() {
  const { session, accessToken } = await requireSession();

  if (session.twoFactorEnabled) {
    return <EnabledView />;
  }

  let enrollment;
  try {
    enrollment = await beginTwoFactorEnrollment(coreAppBaseUrl(), accessToken);
  } catch (error) {
    if (error instanceof ApiError && error.status === 409) {
      return <EnabledView />;
    }
    throw error;
  }
  const { secret, qrCodeUri } = enrollment;

  return (
    <div className="mx-auto max-w-[600px]">
      <BackToProfile />
      <div className="mb-5.5">
        <h1 className="text-[23px] font-semibold tracking-tight text-[var(--text)]">
          Two-factor authentication
        </h1>
        <p className="mt-1.5 text-[14px] text-[var(--text-2)]">
          Secures your Nectrix sign-in with a one-time code, in addition to your password.
        </p>
      </div>

      <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6">
        <div className="mb-5 flex items-center gap-2.5">
          <span className="rounded-full bg-[var(--neg)]/10 px-2.5 py-0.5 text-[12px] font-semibold text-[var(--neg)]">
            Not enabled
          </span>
        </div>

        <div className="mb-5 flex gap-3.5">
          <StepNumber n={1} />
          <div>
            <div className="text-[14px] font-semibold text-[var(--text)]">
              Install an authenticator app
            </div>
            <div className="mt-0.5 text-[12.5px] text-[var(--text-3)]">
              Google Authenticator, Authy, or any TOTP app.
            </div>
          </div>
        </div>

        <div className="mb-5 flex gap-3.5">
          <StepNumber n={2} />
          <div className="flex-1">
            <div className="mb-2.5 text-[14px] font-semibold text-[var(--text)]">
              Scan this QR code
            </div>
            {/* eslint-disable-next-line @next/next/no-img-element -- a data: URI, not a static asset next/image can optimize */}
            <img
              src={qrCodeUri}
              alt="Scan with your authenticator app"
              width={132}
              height={132}
              className="rounded-xl border border-[var(--border)]"
            />
            <p className="mt-2.5 text-[12px] text-[var(--text-2)]">
              Can&apos;t scan? Enter this code manually:{" "}
              <code className="break-all rounded-[6px] bg-[var(--accent-2)] px-1.5 py-0.5 text-[var(--text)]">
                {secret}
              </code>
            </p>
          </div>
        </div>

        <div className="flex gap-3.5">
          <StepNumber n={3} />
          <div className="flex-1">
            <div className="mb-2 text-[14px] font-semibold text-[var(--text)]">
              Enter the 6-digit code
            </div>
            <TwoFactorVerifyForm />
          </div>
        </div>
      </div>
    </div>
  );
}

function StepNumber({ n }: { n: number }) {
  return (
    <div className="flex h-[26px] w-[26px] shrink-0 items-center justify-center rounded-full bg-[var(--accent-2)] text-[12.5px] font-bold text-[var(--accent)]">
      {n}
    </div>
  );
}
